<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PersonajesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // php artisan db:seed --class=PersonajesSeeder
        DB::table('personajes')->insert([
            // *********************** Leo/need ***********************
            [
                'nombre' => 'Ichika Hoshino',
                'grupo_id' => 1,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-ichika.png',
                'chibi' => 'img/personajes/chibi-ichika.png',
                'icon' => 'img/personajes/icon-ichika.png',
                'stamp' => 'img/personajes/stamp-ichika.png',
                'sticker' => 'img/personajes/sticker-ichika.png',
                'comic' => 'img/personajes/comic-ichika.png',
            ],
            [
                'nombre' => 'Saki Tenma',
                'grupo_id' => 1,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-saki.png',
                'chibi' => 'img/personajes/chibi-saki.png',
                'icon' => 'img/personajes/icon-saki.png',
                'stamp' => 'img/personajes/stamp-saki.png',
                'sticker' => 'img/personajes/sticker-saki.png',
                'comic' => 'img/personajes/comic-saki.png',
            ],
            [
                'nombre' => 'Honami Mochizuki',
                'grupo_id' => 1,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-honami.png',
                'chibi' => 'img/personajes/chibi-honami.png',
                'icon' => 'img/personajes/icon-honami.png',
                'stamp' => 'img/personajes/stamp-honami.png',
                'sticker' => 'img/personajes/sticker-honami.png',
                'comic' => 'img/personajes/comic-honami.png',
            ],
            [
                'nombre' => 'Shiho Hinomori',
                'grupo_id' => 1,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-shiho.png',
                'chibi' => 'img/personajes/chibi-shiho.png',
                'icon' => 'img/personajes/icon-shiho.png',
                'stamp' => 'img/personajes/stamp-shiho.png',
                'sticker' => 'img/personajes/sticker-shiho.png',
                'comic' => 'img/personajes/comic-shiho.png',
            ],
            // *********************** MORE MORE JUMP! ***********************
            [
                'nombre' => 'Minori Hanasato',
                'grupo_id' => 2,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-minori.png',
                'chibi' => 'img/personajes/chibi-minori.png',
                'icon' => 'img/personajes/icon-minori.png',
                'stamp' => 'img/personajes/stamp-minori.png',
                'sticker' => 'img/personajes/sticker-minori.png',
                'comic' => 'img/personajes/comic-minori.png',
            ],
            [
                'nombre' => 'Haruka Kiritani',
                'grupo_id' => 2,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-haruka.png',
                'chibi' => 'img/personajes/chibi-haruka.png',
                'icon' => 'img/personajes/icon-haruka.png',
                'stamp' => 'img/personajes/stamp-haruka.png',
                'sticker' => 'img/personajes/sticker-haruka.png',
                'comic' => 'img/personajes/comic-haruka.png',
            ],
            [
                'nombre' => 'Airi Momoi',
                'grupo_id' => 2,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-airi.png',
                'chibi' => 'img/personajes/chibi-airi.png',
                'icon' => 'img/personajes/icon-airi.png',
                'stamp' => 'img/personajes/stamp-airi.png',
                'sticker' => 'img/personajes/sticker-airi.png',
                'comic' => 'img/personajes/comic-airi.png',
            ],
            [
                'nombre' => 'Shizuku Hinomori',
                'grupo_id' => 2,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-shizuku.png',
                'chibi' => 'img/personajes/chibi-shizuku.png',
                'icon' => 'img/personajes/icon-shizuku.png',
                'stamp' => 'img/personajes/stamp-shizuku.png',
                'sticker' => 'img/personajes/sticker-shizuku.png',
                'comic' => 'img/personajes/comic-shizuku.png',
            ],
            // *********************** Vivid BAD SQUAD ***********************
            [
                'nombre' => 'Kohane Azusawa',
                'grupo_id' => 3,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-kohane.png',
                'chibi' => 'img/personajes/chibi-kohane.png',
                'icon' => 'img/personajes/icon-kohane.png',
                'stamp' => 'img/personajes/stamp-kohane.png',
                'sticker' => 'img/personajes/sticker-kohane.png',
                'comic' => 'img/personajes/comic-kohane.png',
            ],
            [
                'nombre' => 'An Shiraishi',
                'grupo_id' => 3,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-an.png',
                'chibi' => 'img/personajes/chibi-an.png',
                'icon' => 'img/personajes/icon-an.png',
                'stamp' => 'img/personajes/stamp-an.png',
                'sticker' => 'img/personajes/sticker-an.png',
                'comic' => 'img/personajes/comic-an.png',
            ],
            [
                'nombre' => 'Akito Shinonome',
                'grupo_id' => 3,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-akito.png',
                'chibi' => 'img/personajes/chibi-akito.png',
                'icon' => 'img/personajes/icon-akito.png',
                'stamp' => 'img/personajes/stamp-akito.png',
                'sticker' => 'img/personajes/sticker-akito.png',
                'comic' => 'img/personajes/comic-akito.png',
            ],
            [
                'nombre' => 'Toya Aoyagi',
                'grupo_id' => 3,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-toya.png',
                'chibi' => 'img/personajes/chibi-toya.png',
                'icon' => 'img/personajes/icon-toya.png',
                'stamp' => 'img/personajes/stamp-toya.png',
                'sticker' => 'img/personajes/sticker-toya.png',
                'comic' => 'img/personajes/comic-toya.png',
            ],
            // *********************** Wonderlands x Showtime ***********************
            [
                'nombre' => 'Tsukasa Tenma',
                'grupo_id' => 4,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-tsukasa.png',
                'chibi' => 'img/personajes/chibi-tsukasa.png',
                'icon' => 'img/personajes/icon-tsukasa.png',
                'stamp' => 'img/personajes/stamp-tsukasa.png',
                'sticker' => 'img/personajes/sticker-tsukasa.png',
                'comic' => 'img/personajes/comic-tsukasa.png',
            ],
            [
                'nombre' => 'Emu Otori',
                'grupo_id' => 4,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-emu.png',
                'chibi' => 'img/personajes/chibi-emu.png',
                'icon' => 'img/personajes/icon-emu.png',
                'stamp' => 'img/personajes/stamp-emu.png',
                'sticker' => 'img/personajes/sticker-emu.png',
                'comic' => 'img/personajes/comic-emu.png',
            ],
            [
                'nombre' => 'Nene Kusanagi',
                'grupo_id' => 4,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-nene.png',
                'chibi' => 'img/personajes/chibi-nene.png',
                'icon' => 'img/personajes/icon-nene.png',
                'stamp' => 'img/personajes/stamp-nene.png',
                'sticker' => 'img/personajes/sticker-nene.png',
                'comic' => 'img/personajes/comic-nene.png',
            ],
            [
                'nombre' => 'Rui Kamishiro',
                'grupo_id' => 4,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-rui.png',
                'chibi' => 'img/personajes/chibi-rui.png',
                'icon' => 'img/personajes/icon-rui.png',
                'stamp' => 'img/personajes/stamp-rui.png',
                'sticker' => 'img/personajes/sticker-rui.png',
                'comic' => 'img/personajes/comic-rui.png',
            ],
            // *********************** Nightcord at 25:00 ***********************
            [
                'nombre' => 'Kanade Yoisaki',
                'grupo_id' => 5,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-kanade.png',
                'chibi' => 'img/personajes/chibi-kanade.png',
                'icon' => 'img/personajes/icon-kanade.png',
                'stamp' => 'img/personajes/stamp-kanade.png',
                'sticker' => 'img/personajes/sticker-kanade.png',
                'comic' => 'img/personajes/comic-kanade.png',
            ],
            [
                'nombre' => 'Mafuyu Asahina',
                'grupo_id' => 5,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-mafuyu.png',
                'chibi' => 'img/personajes/chibi-mafuyu.png',
                'icon' => 'img/personajes/icon-mafuyu.png',
                'stamp' => 'img/personajes/stamp-mafuyu.png',
                'sticker' => 'img/personajes/sticker-mafuyu.png',
                'comic' => 'img/personajes/comic-mafuyu.png',
            ],
            [
                'nombre' => 'Ena Shinonome',
                'grupo_id' => 5,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-ena.png',
                'chibi' => 'img/personajes/chibi-ena.png',
                'icon' => 'img/personajes/icon-ena.png',
                'stamp' => 'img/personajes/stamp-ena.png',
                'sticker' => 'img/personajes/sticker-ena.png',
                'comic' => 'img/personajes/comic-ena.png',
            ],
            [
                'nombre' => 'Mizuki Akiyama',
                'grupo_id' => 5,
                'historia' => 'aaa',
                'personalidad' => 'bbb',
                'imagen' => 'img/personajes/img-mizuki.png',
                'chibi' => 'img/personajes/chibi-mizuki.png',
                'icon' => 'img/personajes/icon-mizuki.png',
                'stamp' => 'img/personajes/stamp-mizuki.png',
                'sticker' => 'img/personajes/sticker-mizuki.png',
                'comic' => 'img/personajes/comic-mizuki.png',
            ],
        ]);
    }
}
